// The deck, as data. Generated by tools/build-content.mjs from the portal's own
// seed files, so the tiles, questions and chart specifications here are the
// client's — not a designer's guess at them.
import raw from './data/content.json';

export type ChartType = 'bar' | 'hbar' | 'line' | 'stacked' | 'pie' | 'map' | 'table';
export type Comparison = 'none' | 'tracked' | 'country';

export interface Wave { year: number; label: string; order: number }
export interface Country { name: string; iso3: string; region: string | null; waves: number[] }
export interface Question {
  code: string; theme: number; text: string; label: string; order: number;
  responseType: string; baseType: string; baseText: string | null;
  tracked: boolean; surfaced: boolean; slide: string | null;
}
export interface ChartSpec {
  theme: number; order: number; title: string; type: ChartType;
  questions: string[]; comparison: Comparison; slide: number | null;
  caveat: string | null; showing: string | null;
}
export interface Theme {
  name: string; slug: string; order: number; accent: string;
  questions: string[]; charts: ChartSpec[];
}

const content = raw as unknown as {
  generatedAt: string; source: string;
  waves: Wave[]; countries: Country[]; themes: Theme[];
  questions: Question[]; charts: ChartSpec[];
};

export const waves = content.waves;
export const countries = content.countries;
export const themes = content.themes;
export const questions = content.questions;

export const latestWave = waves[waves.length - 1]!.year;

const byCode = new Map(questions.map((q) => [q.code, q]));
export const question = (code: string): Question | undefined => byCode.get(code);

const bySlug = new Map(themes.map((t) => [t.slug, t]));
export const theme = (slug: string): Theme | undefined => bySlug.get(slug);
export const themeOf = (q: Question): Theme => themes.find((t) => t.order === q.theme)!;

/** Countries surveyed in a wave. */
export const inWave = (year: number): Country[] =>
  countries.filter((c) => c.waves.includes(year));

/**
 * Countries present in every one of these waves. The portal restricts every
 * cross-wave comparison to this set and says so; the prototype shows the same
 * footnote so the client sees the constraint before the real numbers arrive.
 */
export const likeForLike = (years: number[]): Country[] =>
  countries.filter((c) => years.every((y) => c.waves.includes(y)));
