// The deck, as data. Generated by tools/build-content.mjs from the portal's own
// seed files, so the tiles, questions and chart specifications here are the
// client's — not a designer's guess at them.
import raw from './data/content.json';
import fieldworkRaw from './data/fieldwork.json';

export type ChartType = 'bar' | 'hbar' | 'line' | 'stacked' | 'pie' | 'map' | 'table';
export type Comparison = 'none' | 'tracked' | 'country';

export interface Wave { year: number; label: string; order: number }
export interface Country { name: string; iso3: string; region: string | null; waves: number[] }
export interface Question {
  code: string; theme: number; text: string; label: string; order: number;
  responseType: string; baseType: string; baseText: string | null;
  tracked: boolean; surfaced: boolean; slide: string | null;
  /** The grid this question is a row of, or null. THE-315. */
  parent: string | null;
  /**
   * The waves the portal maps this question in (its crosswave.csv rows), or null
   * when it has none. A grid's rows differ: slide 13's UN is asked only in 2026.
   */
  waves: number[] | null;
}
export interface ChartSpec {
  theme: number; order: number; title: string; type: ChartType;
  questions: string[]; comparison: Comparison; slide: number | null;
  caveat: string | null; showing: string | null;
}
export interface Theme {
  name: string; slug: string; order: number; accent: string;
  questions: string[]; charts: ChartSpec[];
}

const content = raw as unknown as {
  generatedAt: string; source: string;
  waves: Wave[]; countries: Country[]; themes: Theme[];
  questions: Question[]; charts: ChartSpec[];
};

export const waves = content.waves;
export const countries = content.countries;
export const themes = content.themes;
export const questions = content.questions;

export const latestWave = waves[waves.length - 1]!.year;

const byCode = new Map(questions.map((q) => [q.code, q]));
export const question = (code: string): Question | undefined => byCode.get(code);

/**
 * The grid a chart plots, when every question it lists is a row of the same one.
 * A grid's chart lists its children (slide 13's six organisations, slide 43's
 * seven policies), and is drawn from the grid: the deck's options for it are
 * the rows. A chart mixing a grid row with another question (slide 45) is not a
 * grid chart. THE-315.
 */
export function gridOf(codes: string[]): string | null {
  const parents = new Set(codes.map((code) => byCode.get(code)?.parent ?? null));
  const [only] = parents;
  return codes.length > 1 && parents.size === 1 && only ? only : null;
}

/** The questions that are rows of this grid, in seed order. Empty for a question that is not a grid. */
export const childrenOf = (code: string): Question[] => questions.filter((q) => q.parent === code);

/**
 * A grid row's own name: "African Union" for "Positive Influence of Foreign
 * Organisations: African Union". Its label after the grid's, else the row its
 * text names in brackets, else the whole label.
 */
export function rowName(child: Question): string {
  const grid = child.parent ? byCode.get(child.parent) : undefined;
  if (grid && child.label.startsWith(`${grid.label}: `)) return child.label.slice(grid.label.length + 2);
  return /\[([^\]]+)\]\s*$/.exec(child.text)?.[1] ?? child.label;
}

/** Whether a question was asked in a wave. A question with no recorded waves is not narrowed. */
export const askedIn = (q: Question | undefined, year: number): boolean =>
  !q?.waves || q.waves.includes(year);

const bySlug = new Map(themes.map((t) => [t.slug, t]));
export const theme = (slug: string): Theme | undefined => bySlug.get(slug);
export const themeOf = (q: Question): Theme => themes.find((t) => t.order === q.theme)!;

/** Countries surveyed in a wave. */
export const inWave = (year: number): Country[] =>
  countries.filter((c) => c.waves.includes(year));

/**
 * Countries present in every one of these waves. The portal restricts every
 * cross-wave comparison to this set and says so; the prototype shows the same
 * footnote so the client sees the constraint before the real numbers arrive.
 */
export const likeForLike = (years: number[]): Country[] =>
  countries.filter((c) => years.every((y) => c.waves.includes(y)));

/**
 * Who was asked, counted and as supplied. Built by tools/build-fieldwork.py
 * from three sources it names in `source`: the delivered four-wave survey file
 * (interviews per country and wave, unweighted rows), PSB's languages-and-locations
 * list of 28 September (cell text as supplied, gaps left as null), and PSB's four
 * regional groups of 23 September. The generator refuses to write unless the
 * file's country-waves equal the seeded membership above, so a count here can
 * never disagree with `countries[].waves`. These are counts of interviews, not
 * survey results, and the only figures on the site that are not illustrative.
 */
export interface CountryFieldwork {
  /** Interviews achieved, keyed by wave year as a string. */
  interviews: Record<string, number>;
  languages: string | null;
  locations: string | null;
  region: string | null;
  /** What is open with PSB about this country's supplied detail; the page shows it as being checked. */
  query: string | null;
}
export interface WaveFieldwork {
  interviews: number;
  published: number | null;
  /** What is open with PSB about this wave's count; the page flags the figure and says why. */
  query: string | null;
}
export interface Fieldwork {
  source: Record<string, string>;
  waves: Record<string, WaveFieldwork>;
  regions: { name: string; countries: string[] }[];
  countries: Record<string, CountryFieldwork>;
}
export const fieldwork = fieldworkRaw as Fieldwork;
